apiVersion: v1
kind: Secret
metadata:
  name: {{ include "smart-grid.name" . }}-db
  labels:
    {{- include "smart-grid.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.dependencies.postgres.user | quote }}
  password: {{ .Values.dependencies.postgres.password | default "postgres" | quote }}
